# This file contains metadata necessary to scrape different URLs
19hz:
  url: https://19hz.info/eventlisting_BayArea.php
  parser: html5lib
  page-format:
    events:
      format: table
      indices: [0, 1]
      url-mappings:
        start-date-time: [Date/Time]
        end-date-time: [Date/Time]
        geography: [Event Title @ Venue]
        name: [Event Title @ Venue]
        tags: [Tags]
        miscellaneous: [Price | Age, Organizers, Links]
    venues:
      format: table
      indices: [2]
      url-mappings:
        venue-name: [Venue Name]
        venue-address: [Physical Address]
theshrine-nyc:
  url: https://www.shrinenyc.com/
  parser: html.parser
  page-format:
    events:
      format: html


